server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security-practice?createDatabaseIfNotExist=true&useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME_MYSQL}
    password: ${DB_PASSWORD_MYSQL}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

#logging:
#  level:
#    root: INFO
#    org.springframework.web: WARN
#    com.security: INFO
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info
#  endpoint:
#    health:
#      show-details: never